version: '3.8'

services:
  frontend:
    image: evoapicloud/evo-ai-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api-teste.evoapicloud.com
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    restart: unless-stopped 